/**
 * Letter A Words Database
 * Comprehensive collection of words starting with A, categorized by type and length
 * letterawords.github.io
 */

const WORD_DATA = {
  categories: {
    "2-letter": [
      { word: "at", definition: "expressing location or time", partOfSpeech: "preposition" },
      { word: "an", definition: "used before words beginning with a vowel sound", partOfSpeech: "article" },
      { word: "as", definition: "used in comparisons to refer to the extent or degree of something", partOfSpeech: "conjunction" },
      { word: "am", definition: "first person singular present tense of be", partOfSpeech: "verb" },
      { word: "ax", definition: "a tool used for chopping wood", partOfSpeech: "noun" },
      { word: "ad", definition: "an advertisement", partOfSpeech: "noun" },
      { word: "ab", definition: "an abdominal muscle", partOfSpeech: "noun" },
      { word: "ah", definition: "exclamation of surprise or pleasure", partOfSpeech: "exclamation" },
      { word: "ai", definition: "a three-toed sloth", partOfSpeech: "noun" },
    ],
    "3-letter": [
      { word: "ace", definition: "a person who excels at a particular sport or activity", partOfSpeech: "noun" },
      { word: "act", definition: "take action; do something", partOfSpeech: "verb" },
      { word: "add", definition: "join to something already existing", partOfSpeech: "verb" },
      { word: "age", definition: "the length of time a person has lived", partOfSpeech: "noun" },
      { word: "ago", definition: "before the present time", partOfSpeech: "adverb" },
      { word: "aid", definition: "help, typically of a practical nature", partOfSpeech: "noun" },
      { word: "aim", definition: "point or direct at a target", partOfSpeech: "verb" },
      { word: "air", definition: "the invisible gaseous substance surrounding the earth", partOfSpeech: "noun" },
      { word: "all", definition: "used to refer to the whole quantity", partOfSpeech: "predeterminer" },
      { word: "ant", definition: "a small insect that lives in organized colonies", partOfSpeech: "noun" },
      { word: "any", definition: "used to refer to one or some, regardless of quantity", partOfSpeech: "determiner" },
      { word: "ape", definition: "a large primate that lacks a tail", partOfSpeech: "noun" },
      { word: "apt", definition: "appropriate or suitable in the circumstances", partOfSpeech: "adjective" },
      { word: "arc", definition: "a part of the circumference of a circle", partOfSpeech: "noun" },
      { word: "are", definition: "second person singular and plural present of be", partOfSpeech: "verb" },
      { word: "ark", definition: "a large boat or vessel", partOfSpeech: "noun" },
      { word: "arm", definition: "each of the two upper limbs of the human body", partOfSpeech: "noun" },
      { word: "art", definition: "works produced by human creative skill", partOfSpeech: "noun" },
      { word: "ash", definition: "the powdery residue left after burning", partOfSpeech: "noun" },
      { word: "ask", definition: "say something in order to obtain an answer", partOfSpeech: "verb" },
      { word: "axe", definition: "a tool with a metal blade for chopping wood", partOfSpeech: "noun" },
    ],
    "4-letter": [
      { word: "able", definition: "having the power, skill, or means to do something", partOfSpeech: "adjective" },
      { word: "ache", definition: "a continuous or prolonged dull pain", partOfSpeech: "noun" },
      { word: "acid", definition: "a chemical substance with a sour taste", partOfSpeech: "noun" },
      { word: "aged", definition: "having lived for a specified length of time", partOfSpeech: "adjective" },
      { word: "also", definition: "in addition; too", partOfSpeech: "adverb" },
      { word: "area", definition: "a region or part of a town, a country, or the world", partOfSpeech: "noun" },
      { word: "army", definition: "an organized military force equipped for fighting on land", partOfSpeech: "noun" },
      { word: "away", definition: "to or at a distance from a particular place", partOfSpeech: "adverb" },
      { word: "arch", definition: "a curved symmetrical structure spanning an opening", partOfSpeech: "noun" },
      { word: "atom", definition: "the smallest particle of a chemical element", partOfSpeech: "noun" },
      { word: "aunt", definition: "the sister of one's father or mother", partOfSpeech: "noun" },
      { word: "auto", definition: "an automobile or car", partOfSpeech: "noun" },
      { word: "avid", definition: "having or showing a keen interest in something", partOfSpeech: "adjective" },
      { word: "awed", definition: "filled with reverence and wonder", partOfSpeech: "adjective" },
      { word: "axes", definition: "plural of axis or axe", partOfSpeech: "noun" },
      { word: "axis", definition: "an imaginary line about which a body rotates", partOfSpeech: "noun" },
      { word: "axle", definition: "a rod or spindle on which a wheel rotates", partOfSpeech: "noun" },
    ],
    "5-letter": [
      { word: "abide", definition: "accept or act in accordance with a rule or decision", partOfSpeech: "verb" },
      { word: "above", definition: "at a higher level or layer than", partOfSpeech: "preposition" },
      { word: "abuse", definition: "use something to bad effect or for a bad purpose", partOfSpeech: "verb" },
      { word: "acute", definition: "present or experienced to a severe or intense degree", partOfSpeech: "adjective" },
      { word: "adapt", definition: "make suitable for a new use or purpose", partOfSpeech: "verb" },
      { word: "adept", definition: "very skilled or proficient at something", partOfSpeech: "adjective" },
      { word: "adult", definition: "a person who is fully grown or developed", partOfSpeech: "noun" },
      { word: "adorn", definition: "make more beautiful or attractive", partOfSpeech: "verb" },
      { word: "after", definition: "in the time following a particular event", partOfSpeech: "preposition" },
      { word: "again", definition: "another time; once more", partOfSpeech: "adverb" },
      { word: "agent", definition: "a person who acts on behalf of another", partOfSpeech: "noun" },
      { word: "agile", definition: "able to move quickly and easily", partOfSpeech: "adjective" },
      { word: "alarm", definition: "an anxious awareness of danger", partOfSpeech: "noun" },
      { word: "album", definition: "a collection of recordings issued as a single item", partOfSpeech: "noun" },
      { word: "alert", definition: "quick to notice any unusual and potentially dangerous things", partOfSpeech: "adjective" },
      { word: "align", definition: "place or arrange things in a straight line", partOfSpeech: "verb" },
      { word: "alike", definition: "similar to each other", partOfSpeech: "adjective" },
      { word: "alive", definition: "living, not dead", partOfSpeech: "adjective" },
      { word: "aloft", definition: "up in or into the air", partOfSpeech: "adverb" },
      { word: "alone", definition: "having no one else present", partOfSpeech: "adjective" },
      { word: "along", definition: "moving in a constant direction on a path", partOfSpeech: "preposition" },
      { word: "aloud", definition: "audibly; not silently or in a whisper", partOfSpeech: "adverb" },
      { word: "altar", definition: "a table or flat-topped block used in religious services", partOfSpeech: "noun" },
      { word: "amaze", definition: "surprise someone greatly", partOfSpeech: "verb" },
      { word: "amber", definition: "a hard yellowish-brown fossil resin", partOfSpeech: "noun" },
      { word: "amend", definition: "make minor changes in order to make it fairer or more accurate", partOfSpeech: "verb" },
      { word: "angel", definition: "a spiritual being believed to act as a messenger of God", partOfSpeech: "noun" },
      { word: "anger", definition: "a strong feeling of annoyance, displeasure, or hostility", partOfSpeech: "noun" },
      { word: "angle", definition: "the space between two intersecting lines at the point where they meet", partOfSpeech: "noun" },
      { word: "angry", definition: "feeling or showing strong annoyance or hostility", partOfSpeech: "adjective" },
      { word: "annex", definition: "an addition to a building", partOfSpeech: "noun" },
      { word: "anvil", definition: "a heavy iron block used by blacksmiths", partOfSpeech: "noun" },
      { word: "apart", definition: "separated by a distance", partOfSpeech: "adverb" },
      { word: "apple", definition: "the round fruit of the apple tree", partOfSpeech: "noun" },
      { word: "apply", definition: "make a formal application or request", partOfSpeech: "verb" },
      { word: "apron", definition: "a protective garment worn over the front of one's clothes", partOfSpeech: "noun" },
      { word: "arise", definition: "emerge; become apparent", partOfSpeech: "verb" },
      { word: "armor", definition: "metal coverings formerly worn to protect the body in battle", partOfSpeech: "noun" },
      { word: "aroma", definition: "a pleasant and distinctive smell", partOfSpeech: "noun" },
      { word: "array", definition: "an impressive display or range of something", partOfSpeech: "noun" },
      { word: "arrow", definition: "a shaft shot from a bow", partOfSpeech: "noun" },
      { word: "artsy", definition: "having or involving an interest in the arts", partOfSpeech: "adjective" },
      { word: "atlas", definition: "a book of maps or charts", partOfSpeech: "noun" },
      { word: "attic", definition: "a space or room just below the roof of a building", partOfSpeech: "noun" },
      { word: "audio", definition: "sound, especially recorded, transmitted, or reproduced sound", partOfSpeech: "noun" },
      { word: "audit", definition: "an official inspection of an organization's accounts", partOfSpeech: "noun" },
      { word: "aunty", definition: "informal word for aunt", partOfSpeech: "noun" },
      { word: "avail", definition: "help or benefit", partOfSpeech: "verb" },
      { word: "avoid", definition: "keep away from or stop oneself from doing", partOfSpeech: "verb" },
      { word: "aware", definition: "having knowledge or perception of a situation or fact", partOfSpeech: "adjective" },
      { word: "awful", definition: "very bad or unpleasant", partOfSpeech: "adjective" },
    ],
    "6-letter": [
      { word: "abrupt", definition: "sudden and unexpected", partOfSpeech: "adjective" },
      { word: "absorb", definition: "take in or soak up energy, liquid, or other substance", partOfSpeech: "verb" },
      { word: "accent", definition: "a distinctive way of pronouncing a language", partOfSpeech: "noun" },
      { word: "accept", definition: "consent to receive something offered", partOfSpeech: "verb" },
      { word: "access", definition: "the means or opportunity to approach a place or person", partOfSpeech: "noun" },
      { word: "accuse", definition: "charge someone with a fault or crime", partOfSpeech: "verb" },
      { word: "achieve", definition: "successfully bring about or reach a desired objective", partOfSpeech: "verb" },
      { word: "active", definition: "engaging or ready to engage in physically energetic pursuits", partOfSpeech: "adjective" },
      { word: "actual", definition: "existing in fact; typically as contrasted with what was intended", partOfSpeech: "adjective" },
      { word: "adjust", definition: "alter or move something slightly in order to achieve the desired fit", partOfSpeech: "verb" },
      { word: "admire", definition: "regard with respect or warm approval", partOfSpeech: "verb" },
      { word: "affirm", definition: "state as a fact; assert strongly and publicly", partOfSpeech: "verb" },
      { word: "afford", definition: "have enough money to pay for", partOfSpeech: "verb" },
      { word: "agenda", definition: "a list of items to be discussed at a formal meeting", partOfSpeech: "noun" },
      { word: "aerial", definition: "existing, happening, or operating in the air", partOfSpeech: "adjective" },
      { word: "afraid", definition: "feeling fear or anxiety", partOfSpeech: "adjective" },
      { word: "agreed", definition: "agreed upon by all parties; united in opinion", partOfSpeech: "adjective" },
      { word: "allure", definition: "the quality of being powerfully and mysteriously attractive", partOfSpeech: "noun" },
      { word: "almost", definition: "not quite; very nearly", partOfSpeech: "adverb" },
      { word: "always", definition: "at all times; on all occasions", partOfSpeech: "adverb" },
      { word: "anchor", definition: "a heavy object used to moor a vessel to the sea bottom", partOfSpeech: "noun" },
      { word: "annual", definition: "occurring once every year", partOfSpeech: "adjective" },
      { word: "answer", definition: "a thing said, written, or done to deal with a question", partOfSpeech: "noun" },
      { word: "anyone", definition: "any person at all", partOfSpeech: "pronoun" },
      { word: "appear", definition: "come into sight; become visible", partOfSpeech: "verb" },
      { word: "ardent", definition: "enthusiastic or passionate", partOfSpeech: "adjective" },
      { word: "around", definition: "on every side of", partOfSpeech: "preposition" },
      { word: "artful", definition: "clever or skillful, especially in a crafty way", partOfSpeech: "adjective" },
      { word: "assure", definition: "tell someone something positively to dispel doubts", partOfSpeech: "verb" },
      { word: "astern", definition: "behind or toward the rear of a ship", partOfSpeech: "adverb" },
      { word: "astute", definition: "having or showing an ability to accurately assess situations", partOfSpeech: "adjective" },
      { word: "attain", definition: "succeed in achieving something", partOfSpeech: "verb" },
      { word: "autumn", definition: "the third season of the year", partOfSpeech: "noun" },
      { word: "avenue", definition: "a broad road in a town or city, typically having trees at regular intervals", partOfSpeech: "noun" },
      { word: "avidly", definition: "in an eager and enthusiastic manner", partOfSpeech: "adverb" },
      { word: "awaken", definition: "stop sleeping; wake from sleep", partOfSpeech: "verb" },
    ],
    "7-letter": [
      { word: "abandon", definition: "cease to support or look after someone; desert", partOfSpeech: "verb" },
      { word: "ability", definition: "possession of the means or skill to do something", partOfSpeech: "noun" },
      { word: "absence", definition: "the state of being away from a place or person", partOfSpeech: "noun" },
      { word: "absolve", definition: "declare someone free from blame, sin, or responsibility", partOfSpeech: "verb" },
      { word: "account", definition: "a report or description of an event or experience", partOfSpeech: "noun" },
      { word: "achieve", definition: "successfully bring about or reach a desired objective", partOfSpeech: "verb" },
      { word: "acronym", definition: "an abbreviation formed from the initial letters of other words", partOfSpeech: "noun" },
      { word: "address", definition: "the particulars of the place where someone lives", partOfSpeech: "noun" },
      { word: "advance", definition: "move forward, typically in a purposeful way", partOfSpeech: "verb" },
      { word: "adverse", definition: "preventing success or development; harmful; unfavorable", partOfSpeech: "adjective" },
      { word: "advised", definition: "having received advice; prudent or recommended", partOfSpeech: "adjective" },
      { word: "ageless", definition: "never growing or appearing to grow old", partOfSpeech: "adjective" },
      { word: "ailment", definition: "an illness, typically a minor one", partOfSpeech: "noun" },
      { word: "amazing", definition: "causing great surprise or wonder; astonishing", partOfSpeech: "adjective" },
      { word: "amplify", definition: "increase the volume of sound", partOfSpeech: "verb" },
      { word: "ancient", definition: "belonging to the very distant past", partOfSpeech: "adjective" },
      { word: "animate", definition: "give life or energy to", partOfSpeech: "verb" },
      { word: "antique", definition: "a collectable object that is old and often valuable", partOfSpeech: "noun" },
      { word: "anxiety", definition: "a feeling of worry, nervousness, or unease", partOfSpeech: "noun" },
      { word: "anybody", definition: "any person at all", partOfSpeech: "pronoun" },
      { word: "appoint", definition: "assign a job or role to someone", partOfSpeech: "verb" },
      { word: "approve", definition: "officially agree to or accept as satisfactory", partOfSpeech: "verb" },
      { word: "arduous", definition: "involving or requiring strenuous effort; difficult", partOfSpeech: "adjective" },
      { word: "arrange", definition: "put things in a neat, attractive, or required order", partOfSpeech: "verb" },
      { word: "arrival", definition: "the action or process of arriving", partOfSpeech: "noun" },
      { word: "article", definition: "a particular item or object", partOfSpeech: "noun" },
      { word: "artisan", definition: "a worker in a skilled trade who makes products by hand", partOfSpeech: "noun" },
      { word: "artwork", definition: "paintings, drawings, and sculptures", partOfSpeech: "noun" },
      { word: "asphalt", definition: "a mixture of dark bituminous pitch with sand for surfacing roads", partOfSpeech: "noun" },
      { word: "aspire", definition: "direct one's hopes or ambitions toward achieving something", partOfSpeech: "verb" },
      { word: "assault", definition: "a physical attack", partOfSpeech: "noun" },
      { word: "auction", definition: "a public sale in which goods are sold to the highest bidder", partOfSpeech: "noun" },
      { word: "audible", definition: "able to be heard", partOfSpeech: "adjective" },
      { word: "augment", definition: "make something greater by adding to it; increase", partOfSpeech: "verb" },
      { word: "awesome", definition: "extremely impressive or daunting; inspiring awe", partOfSpeech: "adjective" },
    ],
    "8-letter": [
      { word: "absolute", definition: "not qualified or diminished in any way; total", partOfSpeech: "adjective" },
      { word: "abstract", definition: "existing in thought or as an idea but not having a physical existence", partOfSpeech: "adjective" },
      { word: "abundant", definition: "existing or available in large quantities", partOfSpeech: "adjective" },
      { word: "accurate", definition: "correct in all details; exact", partOfSpeech: "adjective" },
      { word: "achieved", definition: "successfully brought about or reached", partOfSpeech: "verb" },
      { word: "activate", definition: "make something active or operative", partOfSpeech: "verb" },
      { word: "adequate", definition: "satisfactory or acceptable in quality or quantity", partOfSpeech: "adjective" },
      { word: "adhesive", definition: "a substance used for sticking objects together; glue", partOfSpeech: "noun" },
      { word: "adjacent", definition: "next to or adjoining something else", partOfSpeech: "adjective" },
      { word: "admirable", definition: "deserving of the highest esteem", partOfSpeech: "adjective" },
      { word: "adorable", definition: "inspiring great affection; delightful; charming", partOfSpeech: "adjective" },
      { word: "advanced", definition: "far on or ahead in development or progress", partOfSpeech: "adjective" },
      { word: "advocate", definition: "a person who publicly supports a particular cause or policy", partOfSpeech: "noun" },
      { word: "affinity", definition: "a natural liking for and understanding of someone or something", partOfSpeech: "noun" },
      { word: "affluent", definition: "wealthy; having a great deal of money", partOfSpeech: "adjective" },
      { word: "agitated", definition: "feeling or appearing troubled or nervous", partOfSpeech: "adjective" },
      { word: "alliance", definition: "a union formed for mutual benefit", partOfSpeech: "noun" },
      { word: "allocate", definition: "distribute resources or duties for a purpose", partOfSpeech: "verb" },
      { word: "allowing", definition: "giving permission for something", partOfSpeech: "verb" },
      { word: "ambition", definition: "a strong desire to do or achieve something", partOfSpeech: "noun" },
      { word: "amenable", definition: "open and responsive to suggestion", partOfSpeech: "adjective" },
      { word: "amiable", definition: "having or displaying a friendly and pleasant manner", partOfSpeech: "adjective" },
      { word: "analysis", definition: "detailed examination of the elements of something", partOfSpeech: "noun" },
      { word: "animated", definition: "full of life or excitement; lively", partOfSpeech: "adjective" },
      { word: "annually", definition: "once a year; every year", partOfSpeech: "adverb" },
      { word: "appetite", definition: "a natural desire to satisfy a bodily need", partOfSpeech: "noun" },
      { word: "applause", definition: "approval or praise expressed by clapping", partOfSpeech: "noun" },
      { word: "approach", definition: "come near or nearer to someone or something in distance", partOfSpeech: "verb" },
      { word: "approval", definition: "the belief that someone or something is good or acceptable", partOfSpeech: "noun" },
      { word: "archives", definition: "a collection of historical documents or records", partOfSpeech: "noun" },
      { word: "aromatic", definition: "having a pleasant and distinctive smell", partOfSpeech: "adjective" },
      { word: "aspirant", definition: "a person who has ambitions to achieve something", partOfSpeech: "noun" },
      { word: "athletic", definition: "physically strong, fit, and active", partOfSpeech: "adjective" },
      { word: "attentive", definition: "paying close attention to something", partOfSpeech: "adjective" },
      { word: "audacity", definition: "a willingness to take bold risks", partOfSpeech: "noun" },
      { word: "autonomy", definition: "the right or condition of self-government", partOfSpeech: "noun" },
    ],
    "9-letter": [
      { word: "abhorrent", definition: "inspiring disgust and loathing; repugnant", partOfSpeech: "adjective" },
      { word: "abolished", definition: "formally put an end to a system, practice, or institution", partOfSpeech: "verb" },
      { word: "abundance", definition: "a very large quantity of something", partOfSpeech: "noun" },
      { word: "acclaimed", definition: "praised enthusiastically and publicly", partOfSpeech: "adjective" },
      { word: "accolade", definition: "an award or privilege granted as a special honor", partOfSpeech: "noun" },
      { word: "accompany", definition: "go somewhere with someone as a companion", partOfSpeech: "verb" },
      { word: "accosting", definition: "approaching and addressing someone boldly", partOfSpeech: "verb" },
      { word: "achievers", definition: "persons who achieve things, especially those who succeed at a high level", partOfSpeech: "noun" },
      { word: "activates", definition: "makes something active or operative", partOfSpeech: "verb" },
      { word: "adaptable", definition: "able to adjust to new conditions", partOfSpeech: "adjective" },
      { word: "addiction", definition: "the fact or condition of being addicted to a substance or activity", partOfSpeech: "noun" },
      { word: "admirable", definition: "arousing or deserving respect and approval", partOfSpeech: "adjective" },
      { word: "admission", definition: "a statement acknowledging the truth of something", partOfSpeech: "noun" },
      { word: "adventure", definition: "an unusual and exciting experience or activity", partOfSpeech: "noun" },
      { word: "affection", definition: "a gentle feeling of fondness or liking", partOfSpeech: "noun" },
      { word: "agendas", definition: "lists of items to be discussed at formal meetings", partOfSpeech: "noun" },
      { word: "aggregate", definition: "a whole formed by combining several elements", partOfSpeech: "noun" },
      { word: "aggrieve", definition: "feel resentment at having been unfairly treated", partOfSpeech: "verb" },
      { word: "algorithm", definition: "a process or set of rules to be followed in problem-solving", partOfSpeech: "noun" },
      { word: "alignment", definition: "arrangement in a straight line or in correct relative positions", partOfSpeech: "noun" },
      { word: "alleviate", definition: "make suffering, deficiency, or a problem less severe", partOfSpeech: "verb" },
      { word: "alongside", definition: "close to the side of; next to", partOfSpeech: "preposition" },
      { word: "altruism", definition: "the belief in or practice of disinterested concern for others", partOfSpeech: "noun" },
      { word: "ambiguous", definition: "open to more than one interpretation; having a double meaning", partOfSpeech: "adjective" },
      { word: "ambitious", definition: "having or showing a strong desire and determination to succeed", partOfSpeech: "adjective" },
      { word: "amiable", definition: "having a friendly pleasant manner", partOfSpeech: "adjective" },
      { word: "amplifier", definition: "an electronic device for increasing the strength of electrical signals", partOfSpeech: "noun" },
      { word: "ancestors", definition: "persons from whom one is descended", partOfSpeech: "noun" },
      { word: "announced", definition: "made a public and typically formal declaration", partOfSpeech: "verb" },
      { word: "anomalous", definition: "deviating from what is standard, normal, or expected", partOfSpeech: "adjective" },
      { word: "anonymous", definition: "not identified by name; of unknown name", partOfSpeech: "adjective" },
      { word: "antiquity", definition: "the ancient past, especially before the Middle Ages", partOfSpeech: "noun" },
      { word: "apparatus", definition: "the technical equipment or machinery needed for a particular activity", partOfSpeech: "noun" },
      { word: "appliance", definition: "a device or piece of equipment designed for a specific task", partOfSpeech: "noun" },
      { word: "archetype", definition: "a very typical example of a certain person or thing", partOfSpeech: "noun" },
      { word: "articulate", definition: "having or showing the ability to speak fluently and coherently", partOfSpeech: "adjective" },
      { word: "aspire", definition: "direct one's hopes or ambitions toward something", partOfSpeech: "verb" },
      { word: "assertive", definition: "having or showing a confident and forceful personality", partOfSpeech: "adjective" },
      { word: "authentic", definition: "of undisputed origin; genuine", partOfSpeech: "adjective" },
      { word: "authorize", definition: "give official permission for or approval to an undertaking", partOfSpeech: "verb" },
      { word: "awareness", definition: "knowledge or perception of a situation or fact", partOfSpeech: "noun" },
    ],
    "10-letter": [
      { word: "absolutely", definition: "with no qualification, restriction, or limitation; totally", partOfSpeech: "adverb" },
      { word: "accomplish", definition: "achieve or complete successfully", partOfSpeech: "verb" },
      { word: "accountant", definition: "a person whose job is to keep or inspect financial accounts", partOfSpeech: "noun" },
      { word: "accredited", definition: "officially recognized as meeting the essential requirements", partOfSpeech: "adjective" },
      { word: "accusation", definition: "a charge or claim that someone has done something wrong", partOfSpeech: "noun" },
      { word: "acclimated", definition: "accustomed to a new climate or new conditions", partOfSpeech: "verb" },
      { word: "additional", definition: "added, extra, or supplementary to what is already present", partOfSpeech: "adjective" },
      { word: "admiration", definition: "respect and warm approval", partOfSpeech: "noun" },
      { word: "adolescent", definition: "a young person in the process of developing from a child into an adult", partOfSpeech: "noun" },
      { word: "affirmable", definition: "capable of being affirmed or asserted", partOfSpeech: "adjective" },
      { word: "aggressive", definition: "ready or likely to attack or confront; hostile", partOfSpeech: "adjective" },
      { word: "alternative", definition: "one or more things available as another possibility", partOfSpeech: "noun" },
      { word: "altogether", definition: "taking everything into account; in total", partOfSpeech: "adverb" },
      { word: "ambassador", definition: "an accredited diplomat sent by a country to another country", partOfSpeech: "noun" },
      { word: "ameliorate", definition: "make something bad or unsatisfactory better", partOfSpeech: "verb" },
      { word: "ammunition", definition: "a supply or quantity of bullets and shells", partOfSpeech: "noun" },
      { word: "annotation", definition: "a note of explanation or comment added to a text", partOfSpeech: "noun" },
      { word: "anticipate", definition: "regard as probable; expect or predict", partOfSpeech: "verb" },
      { word: "apparently", definition: "as far as one knows or can see", partOfSpeech: "adverb" },
      { word: "appreciate", definition: "recognize the full worth of", partOfSpeech: "verb" },
      { word: "apprentice", definition: "a person learning a trade from a skilled employer", partOfSpeech: "noun" },
      { word: "articulate", definition: "express an idea or feeling fluently and coherently", partOfSpeech: "verb" },
      { word: "aspiration", definition: "a hope or ambition of achieving something", partOfSpeech: "noun" },
      { word: "assessment", definition: "the evaluation or estimation of the nature or quality of something", partOfSpeech: "noun" },
      { word: "assiduous", definition: "showing great care and perseverance", partOfSpeech: "adjective" },
      { word: "attraction", definition: "the action or power of evoking interest or liking for something", partOfSpeech: "noun" },
      { word: "attributed", definition: "regarded as being caused by someone or something", partOfSpeech: "verb" },
      { word: "auspicious", definition: "conducive to success; favorable", partOfSpeech: "adjective" },
      { word: "automobile", definition: "a road vehicle, typically with four wheels", partOfSpeech: "noun" },
    ],
  },

  // Positive A words
  positiveWords: [
    { word: "admirable", definition: "deserving the highest esteem and approval" },
    { word: "adorable", definition: "inspiring great affection; delightfully charming" },
    { word: "affectionate", definition: "readily feeling or showing fondness or tenderness" },
    { word: "agile", definition: "able to move quickly and easily; nimble" },
    { word: "agreeable", definition: "pleasant; pleasing to the mind or senses" },
    { word: "altruistic", definition: "showing a disinterested and selfless concern for the well-being of others" },
    { word: "amazing", definition: "causing great surprise or wonder; astonishing" },
    { word: "amicable", definition: "having a spirit of friendliness; without serious disagreement" },
    { word: "amiable", definition: "having or displaying a friendly and pleasant manner" },
    { word: "animated", definition: "full of life or excitement; lively" },
    { word: "apt", definition: "appropriate or suitable in the circumstances" },
    { word: "ardent", definition: "enthusiastic or passionate" },
    { word: "artistic", definition: "having or revealing natural creative skill" },
    { word: "astute", definition: "having or showing an ability to accurately assess situations" },
    { word: "attentive", definition: "paying close attention to something" },
    { word: "audacious", definition: "showing a willingness to take surprisingly bold risks" },
    { word: "authentic", definition: "of undisputed origin; genuine" },
    { word: "avid", definition: "having or showing a keen interest in something" },
    { word: "awesome", definition: "extremely impressive or daunting; inspiring awe" },
    { word: "able", definition: "having the power, skill, or means to do something" },
    { word: "abundant", definition: "existing or available in large quantities; more than enough" },
    { word: "accomplished", definition: "highly trained or skilled in a particular activity" },
    { word: "accurate", definition: "correct in all details; exact" },
    { word: "achieving", definition: "successfully reaching a desired objective" },
    { word: "adaptable", definition: "able to adjust to new conditions" },
  ],

  // Action words (verbs) starting with A
  actionWords: [
    { word: "accelerate", definition: "begin to move more quickly; increase in rate, amount, or extent" },
    { word: "accomplish", definition: "achieve or complete successfully" },
    { word: "achieve", definition: "successfully bring about or reach a desired objective" },
    { word: "act", definition: "take action; do something" },
    { word: "activate", definition: "make something active or operative" },
    { word: "adapt", definition: "make suitable for a new use or purpose" },
    { word: "advance", definition: "move forward, typically in a purposeful way" },
    { word: "advocate", definition: "publicly recommend or support" },
    { word: "affirm", definition: "state as a fact; assert strongly and publicly" },
    { word: "alleviate", definition: "make suffering or a problem less severe" },
    { word: "amplify", definition: "make larger, greater, or louder; increase" },
    { word: "analyze", definition: "examine methodically and in detail" },
    { word: "animate", definition: "bring to life; give life or energy to" },
    { word: "announce", definition: "make a public and typically formal declaration" },
    { word: "apply", definition: "make a formal application or request" },
    { word: "appreciate", definition: "recognize the full worth of something" },
    { word: "articulate", definition: "express an idea fluently and coherently" },
    { word: "aspire", definition: "direct hopes or ambitions toward achieving something" },
    { word: "assemble", definition: "come together; gather or collect" },
    { word: "assist", definition: "help someone to do something; make it easier" },
    { word: "attain", definition: "succeed in achieving something" },
    { word: "attract", definition: "cause to come to a place or participate in something" },
    { word: "authorize", definition: "give official permission or approval" },
    { word: "awaken", definition: "rouse from sleep; cause to stop sleeping" },
  ],

  // A words for kids (simple)
  kidsWords: [
    { word: "ant", definition: "a tiny insect that lives in large groups", emoji: "🐜" },
    { word: "apple", definition: "a round, red or green fruit that grows on trees", emoji: "🍎" },
    { word: "arm", definition: "the part of your body from your shoulder to your hand", emoji: "💪" },
    { word: "art", definition: "drawing, painting, and making beautiful things", emoji: "🎨" },
    { word: "animal", definition: "a living thing that can move and breathe", emoji: "🦁" },
    { word: "airplane", definition: "a vehicle that flies through the sky", emoji: "✈️" },
    { word: "anchor", definition: "a heavy object that keeps a boat from moving", emoji: "⚓" },
    { word: "axe", definition: "a tool used for cutting wood", emoji: "🪓" },
    { word: "acorn", definition: "the small nut that falls from an oak tree", emoji: "🌰" },
    { word: "arrow", definition: "a pointed stick shot from a bow", emoji: "🏹" },
    { word: "avocado", definition: "a green fruit with creamy inside", emoji: "🥑" },
    { word: "astronaut", definition: "a person who travels to space", emoji: "👨‍🚀" },
    { word: "alligator", definition: "a large reptile with sharp teeth", emoji: "🐊" },
    { word: "ambulance", definition: "a vehicle that takes sick people to the hospital", emoji: "🚑" },
    { word: "alphabet", definition: "all the letters we use to write words", emoji: "🔤" },
  ],

  // Scrabble-friendly short A words
  scrabbleWords: [
    { word: "aa", points: 2, definition: "rough lava" },
    { word: "ab", points: 4, definition: "abdominal muscle" },
    { word: "ad", points: 3, definition: "advertisement" },
    { word: "ae", points: 2, definition: "one (Scottish)" },
    { word: "ag", points: 3, definition: "silver (chemistry)" },
    { word: "ah", points: 5, definition: "exclamation" },
    { word: "ai", points: 2, definition: "three-toed sloth" },
    { word: "al", points: 2, definition: "Indian tree" },
    { word: "am", points: 4, definition: "first person of be" },
    { word: "an", points: 2, definition: "indefinite article" },
    { word: "ar", points: 2, definition: "the letter R" },
    { word: "as", points: 2, definition: "conjunction/adverb" },
    { word: "at", points: 2, definition: "preposition" },
    { word: "aw", points: 5, definition: "exclamation" },
    { word: "ax", points: 9, definition: "tool for chopping" },
    { word: "ay", points: 5, definition: "affirmative vote" },
    { word: "ace", points: 5, definition: "expert; score in tennis" },
    { word: "adz", points: 13, definition: "woodworking tool" },
    { word: "aff", points: 9, definition: "off (dialectal)" },
    { word: "aft", points: 6, definition: "at the rear of a ship" },
    { word: "age", points: 4, definition: "period of time" },
    { word: "ago", points: 4, definition: "in the past" },
    { word: "aha", points: 6, definition: "exclamation of discovery" },
    { word: "aid", points: 4, definition: "help or assistance" },
    { word: "aim", points: 5, definition: "point at a target" },
    { word: "ain", points: 3, definition: "own (Scottish)" },
    { word: "air", points: 3, definition: "gaseous atmosphere" },
    { word: "ait", points: 3, definition: "small island" },
    { word: "alb", points: 5, definition: "white ecclesiastical robe" },
    { word: "ale", points: 3, definition: "type of beer" },
  ],
};

// Helper functions for word lookup
const WordUtils = {
  // Get all words as a flat array
  getAllWords() {
    const all = [];
    Object.values(WORD_DATA.categories).forEach(arr => {
      arr.forEach(w => all.push({ ...w, source: "categories" }));
    });
    return all;
  },

  // Search words by query
  search(query) {
    if (!query || query.trim() === "") return [];
    const q = query.toLowerCase().trim();
    const all = this.getAllWords();
    return all.filter(w =>
      w.word.toLowerCase().includes(q) ||
      w.definition.toLowerCase().includes(q)
    );
  },

  // Get words by length
  getByLength(len) {
    const key = `${len}-letter`;
    return WORD_DATA.categories[key] || [];
  },

  // Get words by part of speech
  getByPartOfSpeech(pos) {
    return this.getAllWords().filter(w =>
      w.partOfSpeech && w.partOfSpeech.toLowerCase() === pos.toLowerCase()
    );
  },

  // Get random word
  getRandom() {
    const all = this.getAllWords();
    return all[Math.floor(Math.random() * all.length)];
  },

  // Count total words
  getTotalCount() {
    return this.getAllWords().length;
  },

  // Get words starting with a specific letter combo (e.g., "ab", "ac")
  getByPrefix(prefix) {
    return this.getAllWords().filter(w =>
      w.word.toLowerCase().startsWith(prefix.toLowerCase())
    );
  },
};

// Export for use in other modules
if (typeof module !== "undefined") {
  module.exports = { WORD_DATA, WordUtils };
}
